### PR TITLE
Support datasketch MinHashLSH redis backend

### PR DESCRIPTION
**Pull request by trifle**
Hi,

I noticed that the datasketch library supports redis as a persistence backend for minhashes. That's quite handy, since it allows process restarts and parallel processing.
I've added the interface to MaybeDont - see below.

### CODE REVIEW

**Comment by trifle** [comment]
To add a bit more background: The relevant documentation for datasketch is here: https://ekzhu.github.io/datasketch/lsh.html#minhash-lsh-at-scale

There are some additional configuration options hidden in the code:
https://github.com/ekzhu/datasketch/blob/master/datasketch/storage.py#L238

**Review by lopuhin — APPROVED** [review]

**Comment by lopuhin** [comment]
Thanks @trifle , this is a useful addition! 👍

**Comment by trifle** [comment]
Thanks @lopuhin!
I sort of feel bad about not having tests, but I guess that would require a redis-mocking library etc.
Cheers,
Pascal

**Comment by lopuhin** [comment]
Yes, sure! And I hope this is tested in datasketch itself.

**Pull request merged**
